# Generated by Django 3.2.12 on 2023-03-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatting',
            old_name='title',
            new_name='user',
        ),
    ]
