# Generated by Django 3.2 on 2022-12-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_question_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
