# Generated by Django 3.2 on 2022-12-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221222_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='question',
            new_name='questions',
        ),
    ]
