# Generated by Django 4.1.3 on 2022-12-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/music_file'),
        ),
    ]
